image: registry.gitlab.com/tiltmesenpai/kicad-nightly-runner/kicad-nightly-runner:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

# Sometimes Gitlab CI sorta... just forgets to pull the tags? (gitlab-org/gitaly#2221)
before_script:
  - git describe --tags || git fetch --tags

build_gerbers:
  script: 
  - /usr/bin/plot_gerbers.py mini-mipi.kicad_pcb $(git describe --tags)
  artifacts:
    paths:
    - plot
