# This is a basic workflow to help you get started with Actions

name: Plot Gerbers

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Plot Gerbers
      uses: TiltMeSenpai/kicad-nightly-create-gerbers@dev
      with:
        pcb-file: mini-mipi.kicad_pcb

    # Runs a set of commands using the runners shell
    - name: Upload Gerbers
      uses: actions/upload-artifact@v1
      with:
        name: gerbers
        path: plot
